# - META -------------------------------------
# MONOBIOME          :mode=dark :contrast=hard
# BADLANDS
#
# pat  ::  < 0-bg-3 > | gra | acc | < 3-fg-0 >
# abs  ::  min -- +15 | +30 | +40 | +50 -- +65
# rel  ::  min -- +15 | +15 | +10 | +10 -- +15
# sys  ::  l15 -- l30 | l45 | l55 | l65 -- l80
# app  ::  l20 -- l35 | l50 | l60 | l70 -- l85

mode         = "dark"
biome        = "badlands"
contrast     = "hard"
# --------------------------------------------

# - SYS --------------------------------------
bg0          = "f{{badlands.l15}}"   # < MIN >
bg1          = "f{{badlands.l20}}"   # < +05 >
bg2          = "f{{badlands.l25}}"   # < +10 >
bg3          = "f{{badlands.l30}}"   # < +15 >

grey         = "f{{badlands.l45}}"   # < +30 >

red          = "f{{red.l55}}"        # < +40 >
orange       = "f{{orange.l55}}"     # < +40 >
yellow       = "f{{yellow.l55}}"     # < +40 >
green        = "f{{green.l55}}"      # < +40 >
cyan         = "f{{green.l55}}"      # < +40 >
blue         = "f{{blue.l55}}"       # < +40 >
violet       = "f{{blue.l55}}"       # < +40 >
magenta      = "f{{red.l55}}"        # < +40 >

fg3          = "f{{badlands.l65}}"   # < +50 >
fg2          = "f{{badlands.l70}}"   # < +55 >
fg1          = "f{{badlands.l75}}"   # < +60 >
fg0          = "f{{badlands.l80}}"   # < MAX >
# --------------------------------------------

# - APP --------------------------------------
[term]
foreground   = "f{{badlands.l85}}"   # < MAX >
selection_fg = "f{{badlands.l80}}"   # < -05 >

background   = "f{{badlands.l20}}"   # < MIN >
selection_bg = "f{{badlands.l25}}"   # < +05 >

cursor       = "f{{badlands.l80}}"   # <MAX-5>
cursor_text  = "f{{badlands.l25}}"   # <MIN+5>

[term.normal]
black        = "f{{badlands.l20}}"   # < MIN >
red          = "f{{red.l60}}"        # < +40 >
green        = "f{{green.l60}}"      # < +40 >
yellow       = "f{{yellow.l60}}"     # < +40 >
blue         = "f{{blue.l60}}"       # < +40 >
magenta      = "f{{orange.l60}}"     # < +40 >
cyan         = "f{{blue.l60}}"       # < +40 >
white        = "f{{badlands.l75}}"   # < +55 >

[term.bright]
black        = "f{{badlands.l30}}"   # < +10 >
red          = "f{{red.l70}}"        # < +50 >
green        = "f{{green.l70}}"      # < +50 >
yellow       = "f{{yellow.l70}}"     # < +50 >
blue         = "f{{blue.l70}}"       # < +50 >
magenta      = "f{{orange.l70}}"     # < +50 >
cyan         = "f{{blue.l70}}"       # < +50 >
white        = "f{{badlands.l85}}"   # < MAX >

[vim]
bg0          = "f{{badlands.l20}}"   # < MIN >
bg1          = "f{{badlands.l25}}"   # < +05 >
bg2          = "f{{badlands.l30}}"   # < +10 >
bg3          = "f{{badlands.l35}}"   # < +15 >

grey         = "f{{badlands.l50}}"   # < +30 >

red          = "f{{red.l60}}"        # < +40 >
orange       = "f{{orange.l60}}"     # < +40 >
yellow       = "f{{yellow.l60}}"     # < +40 >
green        = "f{{green.l60}}"      # < +40 >
cyan         = "f{{green.l60}}"      # < +40 >
blue         = "f{{blue.l60}}"       # < +40 >
violet       = "f{{blue.l60}}"       # < +40 >
magenta      = "f{{red.l60}}"        # < +40 >

fg3          = "f{{badlands.l70}}"   # < +50 >
fg2          = "f{{badlands.l75}}"   # < +55 >
fg1          = "f{{badlands.l80}}"   # < +60 >
fg0          = "f{{badlands.l85}}"   # < MAX >
# --------------------------------------------
