# - META -------------------------------------
# MONOBIOME      :mode=light :contrast=default
# CHAPARRAL
#
# pat  ::  < 0-bg-3 > | gra | acc | < 3-fg-0 >
# abs  ::  max -- -15 | -30 | -40 | -50 -- -65
# rel  ::  max -- -15 | -15 | -10 | -10 -- -15
# sys  ::  l85 -- l70 | l55 | l45 | l35 -- l20
# app  ::  l90 -- l75 | l60 | l50 | l40 -- l25
# --------------------------------------------

# - SYS --------------------------------------
bg0          = "f{{chaparral.l85}}"  # < MAX >
bg1          = "f{{chaparral.l80}}"  # < -05 >
bg2          = "f{{chaparral.l75}}"  # < -10 >
bg3          = "f{{chaparral.l70}}"  # < -15 >

grey         = "f{{chaparral.l55}}"  # < -30 >

red          = "f{{red.l45}}"        # < -40 >
orange       = "f{{orange.l45}}"     # < -40 >
yellow       = "f{{yellow.l45}}"     # < -40 >
green        = "f{{green.l45}}"      # < -40 >
cyan         = "f{{green.l45}}"      # < -40 >
blue         = "f{{blue.l45}}"       # < -40 >
violet       = "f{{blue.l45}}"       # < -40 >
magenta      = "f{{red.l45}}"        # < -40 >

fg3          = "f{{chaparral.l35}}"  # < -50 >
fg2          = "f{{chaparral.l30}}"  # < -55 >
fg1          = "f{{chaparral.l25}}"  # < -60 >
fg0          = "f{{chaparral.l20}}"  # < MIN >
# --------------------------------------------

# - APP --------------------------------------
[term]
foreground   = "f{{chaparral.l25}}"  # < MIN >
selection_fg = "f{{chaparral.l30}}"  # < +05 >

background   = "f{{chaparral.l90}}"  # < MAX >
selection_bg = "f{{chaparral.l85}}"  # < -05 >

cursor       = "f{{chaparral.l30}}"  # <MIN+5>
cursor_text  = "f{{chaparral.l85}}"  # <MAX-5>

[term.normal]
black        = "f{{chaparral.l90}}"  # < MAX >
red          = "f{{red.l50}}"        # < -40 >
green        = "f{{green.l50}}"      # < -40 >
yellow       = "f{{yellow.l50}}"     # < -40 >
blue         = "f{{blue.l50}}"       # < -40 >
magenta      = "f{{orange.l50}}"     # < -40 >
cyan         = "f{{blue.l50}}"       # < -40 >
white        = "f{{chaparral.l35}}"  # < -55 >

[term.bright]
black        = "f{{chaparral.l80}}"  # < -10 >
red          = "f{{red.l40}}"        # < -50 >
green        = "f{{green.l40}}"      # < -50 >
yellow       = "f{{yellow.l40}}"     # < -50 >
blue         = "f{{blue.l40}}"       # < -50 >
magenta      = "f{{orange.l40}}"     # < -50 >
cyan         = "f{{blue.l40}}"       # < -50 >
white        = "f{{chaparral.l25}}"  # < MIN >

[vim]
bg0          = "f{{chaparral.l90}}"  # < MAX >
bg1          = "f{{chaparral.l85}}"  # < -05 >
bg2          = "f{{chaparral.l80}}"  # < -10 >
bg3          = "f{{chaparral.l75}}"  # < -15 >

grey         = "f{{chaparral.l60}}"  # < -30 >

red          = "f{{red.l50}}"        # < -40 >
orange       = "f{{orange.l50}}"     # < -40 >
yellow       = "f{{yellow.l50}}"     # < -40 >
green        = "f{{green.l50}}"      # < -40 >
cyan         = "f{{green.l50}}"      # < -40 >
blue         = "f{{blue.l50}}"       # < -40 >
violet       = "f{{blue.l50}}"       # < -40 >
magenta      = "f{{red.l50}}"        # < -40 >

fg3          = "f{{chaparral.l40}}"  # < -50 >
fg2          = "f{{chaparral.l35}}"  # < -55 >
fg1          = "f{{chaparral.l30}}"  # < -60 >
fg0          = "f{{chaparral.l25}}"  # < MIN >
# --------------------------------------------
