# - META -------------------------------------
# MONOBIOME         :mode=dark :harshness=soft
# GRASSLAND              :contrast=WCAG 2.2 AA
#
# pat  ::  < 0-bg-3 > | gra | acc | < 3-fg-0 >
# abs  ::  min -- +15 | +30 | +40 | +50 -- +65
# rel  ::  min -- +15 | +15 | +10 | +10 -- +15
# sys  ::  l25 -- l40 | l55 | l65 | l75 -- l90
# app  ::  l30 -- l45 | l60 | l70 | l80 -- l95

mode         = "dark"
biome        = "grassland"
contrast     = "soft"
# --------------------------------------------

# - SYS --------------------------------------
bg0          = "f{{grassland.l25}}"  # < MIN >
bg1          = "f{{grassland.l30}}"  # < +05 >
bg2          = "f{{grassland.l35}}"  # < +10 >
bg3          = "f{{grassland.l30}}"  # < +15 >

grey         = "f{{grassland.l55}}"  # < +30 >

red          = "f{{red.l65}}"        # < +40 >
orange       = "f{{orange.l65}}"     # < +40 >
yellow       = "f{{yellow.l65}}"     # < +40 >
green        = "f{{green.l65}}"      # < +40 >
cyan         = "f{{green.l65}}"      # < +40 >
blue         = "f{{blue.l65}}"       # < +40 >
violet       = "f{{blue.l65}}"       # < +40 >
magenta      = "f{{red.l65}}"        # < +40 >

fg3          = "f{{grassland.l75}}"  # < +50 >
fg2          = "f{{grassland.l80}}"  # < +55 >
fg1          = "f{{grassland.l85}}"  # < +60 >
fg0          = "f{{grassland.l90}}"  # < MAX >
# --------------------------------------------

# - APP --------------------------------------
[term]
foreground   = "f{{grassland.l95}}"  # < MAX >
selection_fg = "f{{grassland.l90}}"  # < -05 >

background   = "f{{grassland.l30}}"  # < MIN >
selection_bg = "f{{grassland.l35}}"  # < +05 >

cursor       = "f{{grassland.l90}}"  # <MAX-5>
cursor_text  = "f{{grassland.l35}}"  # <MIN+5>

[term.normal]
black        = "f{{grassland.l30}}"  # < MIN >
red          = "f{{red.l70}}"        # < +40 >
green        = "f{{green.l70}}"      # < +40 >
yellow       = "f{{yellow.l70}}"     # < +40 >
blue         = "f{{blue.l70}}"       # < +40 >
magenta      = "f{{orange.l70}}"     # < +40 >
cyan         = "f{{blue.l70}}"       # < +40 >
white        = "f{{grassland.l85}}"  # < +55 >

[term.bright]
black        = "f{{grassland.l40}}"  # < +10 >
red          = "f{{red.l80}}"        # < +50 >
green        = "f{{green.l80}}"      # < +50 >
yellow       = "f{{yellow.l80}}"     # < +50 >
blue         = "f{{blue.l80}}"       # < +50 >
magenta      = "f{{orange.l80}}"     # < +50 >
cyan         = "f{{blue.l80}}"       # < +50 >
white        = "f{{grassland.l95}}"  # < MAX >

[vim]
bg0          = "f{{grassland.l30}}"  # < MIN >
bg1          = "f{{grassland.l35}}"  # < +05 >
bg2          = "f{{grassland.l40}}"  # < +10 >
bg3          = "f{{grassland.l45}}"  # < +15 >

grey         = "f{{grassland.l60}}"  # < +30 >

red          = "f{{red.l70}}"        # < +40 >
orange       = "f{{orange.l70}}"     # < +40 >
yellow       = "f{{yellow.l70}}"     # < +40 >
green        = "f{{green.l70}}"      # < +40 >
cyan         = "f{{green.l70}}"      # < +40 >
blue         = "f{{blue.l70}}"       # < +40 >
violet       = "f{{blue.l70}}"       # < +40 >
magenta      = "f{{red.l70}}"        # < +40 >

fg3          = "f{{grassland.l80}}"  # < +50 >
fg2          = "f{{grassland.l85}}"  # < +55 >
fg1          = "f{{grassland.l90}}"  # < +60 >
fg0          = "f{{grassland.l95}}"  # < MAX >
# --------------------------------------------
