# - META -------------------------------------
# MONOBIOME          :mode=dark :contrast=soft
# TUNDRA 
#
# pat  ::  < 0-bg-3 > | gra | acc | < 3-fg-0 >
# abs  ::  min -- +15 | +30 | +40 | +50 -- +65
# rel  ::  min -- +15 | +15 | +10 | +10 -- +15
# sys  ::  l25 -- l40 | l55 | l65 | l75 -- l90
# app  ::  l30 -- l45 | l60 | l70 | l80 -- l95
# --------------------------------------------

# - SYS --------------------------------------
bg0          = "f{{tundra.l25}}"     # < MIN >
bg1          = "f{{tundra.l30}}"     # < +05 >
bg2          = "f{{tundra.l35}}"     # < +10 >
bg3          = "f{{tundra.l30}}"     # < +15 >

grey         = "f{{tundra.l55}}"     # < +30 >

red          = "f{{red.l65}}"        # < +40 >
orange       = "f{{orange.l65}}"     # < +40 >
yellow       = "f{{yellow.l65}}"     # < +40 >
green        = "f{{green.l65}}"      # < +40 >
cyan         = "f{{green.l65}}"      # < +40 >
blue         = "f{{blue.l65}}"       # < +40 >
violet       = "f{{blue.l65}}"       # < +40 >
magenta      = "f{{red.l65}}"        # < +40 >

fg3          = "f{{tundra.l75}}"     # < +50 >
fg2          = "f{{tundra.l80}}"     # < +55 >
fg1          = "f{{tundra.l85}}"     # < +60 >
fg0          = "f{{tundra.l90}}"     # < MAX >
# --------------------------------------------

# - APP --------------------------------------
[term]
foreground   = "f{{tundra.l95}}"     # < MAX >
selection_fg = "f{{tundra.l90}}"     # < -05 >

background   = "f{{tundra.l30}}"     # < MIN >
selection_bg = "f{{tundra.l35}}"     # < +05 >

cursor       = "f{{tundra.l90}}"     # <MAX-5>
cursor_text  = "f{{tundra.l35}}"     # <MIN+5>

[term.normal]
black        = "f{{tundra.l30}}"     # < MIN >
red          = "f{{red.l70}}"        # < +40 >
green        = "f{{green.l70}}"      # < +40 >
yellow       = "f{{yellow.l70}}"     # < +40 >
blue         = "f{{blue.l70}}"       # < +40 >
magenta      = "f{{orange.l70}}"     # < +40 >
cyan         = "f{{blue.l70}}"       # < +40 >
white        = "f{{tundra.l85}}"     # < +55 >

[term.bright]
black        = "f{{tundra.l40}}"     # < +10 >
red          = "f{{red.l80}}"        # < +50 >
green        = "f{{green.l80}}"      # < +50 >
yellow       = "f{{yellow.l80}}"     # < +50 >
blue         = "f{{blue.l80}}"       # < +50 >
magenta      = "f{{orange.l80}}"     # < +50 >
cyan         = "f{{blue.l80}}"       # < +50 >
white        = "f{{tundra.l95}}"     # < MAX >

[vim]
bg0          = "f{{tundra.l30}}"     # < MIN >
bg1          = "f{{tundra.l35}}"     # < +05 >
bg2          = "f{{tundra.l40}}"     # < +10 >
bg3          = "f{{tundra.l45}}"     # < +15 >

grey         = "f{{tundra.l60}}"     # < +30 >

red          = "f{{red.l70}}"        # < +40 >
orange       = "f{{orange.l70}}"     # < +40 >
yellow       = "f{{yellow.l70}}"     # < +40 >
green        = "f{{green.l70}}"      # < +40 >
cyan         = "f{{green.l70}}"      # < +40 >
blue         = "f{{blue.l70}}"       # < +40 >
violet       = "f{{blue.l70}}"       # < +40 >
magenta      = "f{{red.l70}}"        # < +40 >

fg3          = "f{{tundra.l80}}"     # < +50 >
fg2          = "f{{tundra.l85}}"     # < +55 >
fg1          = "f{{tundra.l90}}"     # < +60 >
fg0          = "f{{tundra.l95}}"     # < MAX >
# --------------------------------------------
