bg0 = "f{{grassland.l90}}" # darkest
bg1 = "f{{grassland.l85}}"
bg2 = "f{{grassland.l80}}"
bg3 = "f{{grassland.l75}}"

grey = "f{{grassland.l60}}" # <bg3 - 15>

fg3 = "f{{grassland.l40}}"
fg2 = "f{{grassland.l35}}"
fg1 = "f{{grassland.l30}}"
fg0 = "f{{grassland.l25}}" # lightest

red     = "f{{red.l50}}"
orange  = "f{{orange.l50}}"
yellow  = "f{{yellow.l50}}"
green   = "f{{green.l50}}"
cyan    = "f{{green.l50}}"
blue    = "f{{blue.l50}}"
violet  = "f{{blue.l50}}"
magenta = "f{{red.l50}}"

[term]
background        = "f{{grassland.l85}}" # <bg0 - 5>
foreground        = "f{{grassland.l20}}" # <fg0 - 5>

selection_bg      = "f{{grassland.l80}}" # <bg1 - 5>
selection_fg      = "f{{grassland.l25}}" # <fg1 - 5>

cursor            = "f{{grassland.l25}}" # <fg1 - 5>
cursor_text_color = "f{{grassland.l80}}" # <bg1 - 5>

[term.normal]
black  = "f{{grassland.l20}}" # <foreground>
red    = "f{{red.l50}}"
green  = "f{{green.l50}}"
yellow = "f{{yellow.l50}}"
blue   = "f{{blue.l50}}"
purple = "f{{orange.l50}}"
cyan   = "f{{blue.l50}}"
white  = "f{{grassland.l75}}" # <background - 10>

[term.bright]
black  = "f{{grassland.l30}}" # <foreground + 10>
red    = "f{{red.l50}}"
green  = "f{{green.l50}}"
yellow = "f{{yellow.l50}}"
blue   = "f{{blue.l50}}"
purple = "f{{orange.l50}}"
cyan   = "f{{blue.l50}}"
white  = "f{{grassland.l85}}" # <background>

[vim]
bg0 = "f{{grassland.l85}}" # <bg0 - 5>
bg1 = "f{{grassland.l80}}" # <bg1 - 5>
bg2 = "f{{grassland.l75}}" # <bg2 - 5>
bg3 = "f{{grassland.l70}}" # <bg3 - 5>

grey = "f{{grassland.l50}}" # <grey - 5>

fg3 = "f{{grassland.l35}}" # <fg0 - 5>
fg2 = "f{{grassland.l30}}" # <fg1 - 5>
fg1 = "f{{grassland.l25}}" # <fg2 - 5>
fg0 = "f{{grassland.l20}}" # <fg3 - 5>

red     = "f{{red.l50}}"
orange  = "f{{orange.l50}}"
yellow  = "f{{yellow.l50}}"
green   = "f{{green.l50}}"
cyan    = "f{{green.l50}}"
blue    = "f{{blue.l50}}"
violet  = "f{{blue.l50}}"
magenta = "f{{red.l50}}"
