bg0 = "f{{savanna.l15}}" # darkest
bg1 = "f{{savanna.l20}}"
bg2 = "f{{savanna.l25}}"
bg3 = "f{{savanna.l30}}"

grey = "f{{savanna.l45}}" # <bg3 + 15>

fg3 = "f{{savanna.l65}}"
fg2 = "f{{savanna.l70}}"
fg1 = "f{{savanna.l75}}"
fg0 = "f{{savanna.l80}}" # lightest

red     = "f{{red.l60}}"
orange  = "f{{orange.l60}}"
yellow  = "f{{yellow.l60}}"
green   = "f{{green.l60}}"
cyan    = "f{{green.l60}}"
blue    = "f{{blue.l60}}"
violet  = "f{{blue.l60}}"
magenta = "f{{red.l60}}"

[term]
background        = "f{{savanna.l20}}" # <bg0 + 5>
foreground        = "f{{savanna.l85}}" # <fg0 + 5>

selection_bg      = "f{{savanna.l25}}" # <bg1 + 5>
selection_fg      = "f{{savanna.l80}}" # <fg1 + 5>

cursor            = "f{{savanna.l80}}" # <fg1 + 5>
cursor_text_color = "f{{savanna.l25}}" # <bg1 + 5>

[term.normal]
black  = "f{{savanna.l20}}" # <background>
red    = "f{{red.l60}}"
green  = "f{{green.l60}}"
yellow = "f{{yellow.l60}}"
blue   = "f{{blue.l60}}"
purple = "f{{orange.l60}}"
cyan   = "f{{blue.l60}}"
white  = "f{{savanna.l75}}" # <foreground - 10>

[term.bright]
black  = "f{{savanna.l30}}" # <background + 10>
red    = "f{{red.l70}}"
green  = "f{{green.l70}}"
yellow = "f{{yellow.l70}}"
blue   = "f{{blue.l70}}"
purple = "f{{orange.l70}}"
cyan   = "f{{blue.l70}}"
white  = "f{{savanna.l85}}" # <foreground>

[vim]
bg0 = "f{{savanna.l20}}" # <bg0 + 5>
bg1 = "f{{savanna.l25}}" # <bg1 + 5>
bg2 = "f{{savanna.l30}}" # <bg2 + 5>
bg3 = "f{{savanna.l35}}" # <bg3 + 5>

grey = "f{{savanna.l55}}" # <grey + 5>

fg3 = "f{{savanna.l70}}" # <fg0 + 5>
fg2 = "f{{savanna.l75}}" # <fg1 + 5>
fg1 = "f{{savanna.l80}}" # <fg2 + 5>
fg0 = "f{{savanna.l85}}" # <fg3 + 5>

red     = "f{{red.l60}}"
orange  = "f{{orange.l60}}"
yellow  = "f{{yellow.l60}}"
green   = "f{{green.l60}}"
cyan    = "f{{green.l60}}"
blue    = "f{{blue.l60}}"
violet  = "f{{blue.l60}}"
magenta = "f{{red.l60}}"
