bg0 = "f{{grassland.l85}}" # darkest
bg1 = "f{{grassland.l80}}"
bg2 = "f{{grassland.l75}}"
bg3 = "f{{grassland.l70}}"

grey = "f{{grassland.l55}}" # <bg3 - 15>

fg3 = "f{{grassland.l35}}"
fg2 = "f{{grassland.l30}}"
fg1 = "f{{grassland.l25}}"
fg0 = "f{{grassland.l20}}" # lightest

red     = "f{{red.l45}}"
orange  = "f{{orange.l45}}"
yellow  = "f{{yellow.l45}}"
green   = "f{{green.l45}}"
cyan    = "f{{green.l45}}"
blue    = "f{{blue.l45}}"
violet  = "f{{blue.l45}}"
magenta = "f{{red.l45}}"

[term]
background        = "f{{grassland.l80}}" # <bg0 - 5>
foreground        = "f{{grassland.l15}}" # <fg0 - 5>

selection_bg      = "f{{grassland.l75}}" # <bg1 - 5>
selection_fg      = "f{{grassland.l20}}" # <fg1 - 5>

cursor            = "f{{grassland.l20}}" # <fg1 - 5>
cursor_text_color = "f{{grassland.l75}}" # <bg1 - 5>

[term.normal]
black  = "f{{grassland.l15}}" # <foreground>
red    = "f{{red.l45}}"
green  = "f{{green.l45}}"
yellow = "f{{yellow.l45}}"
blue   = "f{{blue.l45}}"
purple = "f{{orange.l45}}"
cyan   = "f{{blue.l45}}"
white  = "f{{grassland.l70}}" # <background - 10>

[term.bright]
black  = "f{{grassland.l25}}" # <foreground + 10>
red    = "f{{red.l45}}"
green  = "f{{green.l45}}"
yellow = "f{{yellow.l45}}"
blue   = "f{{blue.l45}}"
purple = "f{{orange.l45}}"
cyan   = "f{{blue.l45}}"
white  = "f{{grassland.l80}}" # <background>

[vim]
bg0 = "f{{grassland.l80}}" # <bg0 - 5>
bg1 = "f{{grassland.l75}}" # <bg1 - 5>
bg2 = "f{{grassland.l70}}" # <bg2 - 5>
bg3 = "f{{grassland.l65}}" # <bg3 - 5>

grey = "f{{grassland.l45}}" # <grey - 5>

fg3 = "f{{grassland.l30}}" # <fg0 - 5>
fg2 = "f{{grassland.l25}}" # <fg1 - 5>
fg1 = "f{{grassland.l20}}" # <fg2 - 5>
fg0 = "f{{grassland.l15}}" # <fg3 - 5>

red     = "f{{red.l45}}"
orange  = "f{{orange.l45}}"
yellow  = "f{{yellow.l45}}"
green   = "f{{green.l45}}"
cyan    = "f{{green.l45}}"
blue    = "f{{blue.l45}}"
violet  = "f{{blue.l45}}"
magenta = "f{{red.l45}}"
