bg0 = "f{{default.l25}}" # darkest
bg1 = "f{{default.l30}}"
bg2 = "f{{default.l35}}"
bg3 = "f{{default.l40}}"

grey = "f{{default.l55}}" # <bg3 + 15>

fg3 = "f{{default.l75}}"
fg2 = "f{{default.l80}}"
fg1 = "f{{default.l85}}"
fg0 = "f{{default.l90}}" # lightest

red     = "f{{red.l70}}"
orange  = "f{{orange.l70}}"
yellow  = "f{{yellow.l70}}"
green   = "f{{green.l70}}"
cyan    = "f{{green.l70}}"
blue    = "f{{blue.l70}}"
violet  = "f{{blue.l70}}"
magenta = "f{{red.l70}}"

[term]
background        = "f{{default.l30}}" # <bg0 + 5>
foreground        = "f{{default.l95}}" # <fg0 + 5>

selection_bg      = "f{{default.l35}}" # <bg1 + 5>
selection_fg      = "f{{default.l90}}" # <fg1 + 5>

cursor            = "f{{default.l90}}" # <fg1 + 5>
cursor_text_color = "f{{default.l35}}" # <bg1 + 5>

[term.normal]
black  = "f{{default.l30}}" # <background>
red    = "f{{red.l70}}"
green  = "f{{green.l70}}"
yellow = "f{{yellow.l70}}"
blue   = "f{{blue.l70}}"
purple = "f{{orange.l70}}"
cyan   = "f{{blue.l70}}"
white  = "f{{default.l85}}" # <foreground - 10>

[term.bright]
black  = "f{{default.l40}}" # <background + 10>
red    = "f{{red.l80}}"
green  = "f{{green.l80}}"
yellow = "f{{yellow.l80}}"
blue   = "f{{blue.l80}}"
purple = "f{{orange.l80}}"
cyan   = "f{{blue.l80}}"
white  = "f{{default.l95}}" # <foreground>

[vim]
bg0 = "f{{default.l30}}" # <bg0 + 5>
bg1 = "f{{default.l35}}" # <bg1 + 5>
bg2 = "f{{default.l40}}" # <bg2 + 5>
bg3 = "f{{default.l45}}" # <bg3 + 5>

grey = "f{{default.l65}}" # <grey + 5>

fg3 = "f{{default.l80}}" # <fg0 + 5>
fg2 = "f{{default.l85}}" # <fg1 + 5>
fg1 = "f{{default.l90}}" # <fg2 + 5>
fg0 = "f{{default.l95}}" # <fg3 + 5>

red     = "f{{red.l70}}"
orange  = "f{{orange.l70}}"
yellow  = "f{{yellow.l70}}"
green   = "f{{green.l70}}"
cyan    = "f{{green.l70}}"
blue    = "f{{blue.l70}}"
violet  = "f{{blue.l70}}"
magenta = "f{{red.l70}}"
