# base settings
background           #e5dbda
foreground           #27201f

selection_background #d5cbca
selection_foreground #332c2b

cursor               #332c2b
cursor_text          #d5cbca

# black
color0               #e5dbda
color8               #c5bbba

# red
color1               #b42219
color9               #85160f

# green
color2               #377242
color10              #25532e

# yellow
color3               #6a6535
color11              #4c4928

# blue
color4               #3860ac
color12              #234485

# magenta (red)
color5               #905201
color13              #673c0c

# cyan (blue)
color6               #3860ac
color14              #234485

## white
color7               #403837
color15              #27201f
