# base settings
background           #eaeff6
foreground           #2b2e33

selection_background #dadee6
selection_foreground #373b40

cursor               #373b40
cursor_text          #dadee6

# black
color0               #eaeff6
color8               #caced5

# red
color1               #ca2f24
color9               #9d1a13

# green
color2               #42824e
color10              #2e6337

# yellow
color3               #79743d
color11              #5b572e

# blue
color4               #456fbe
color12              #2d5299

# magenta (red)
color5               #a45e03
color13              #7c4706

# cyan (blue)
color6               #456fbe
color14              #2d5299

## white
color7               #44484e
color15              #2b2e33
