# base settings
background           #dedede
foreground           #222222

selection_background #cecece
selection_foreground #2e2e2e

cursor               #2e2e2e
cursor_text          #cecece

# black
color0               #dedede
color8               #bebebe

# red
color1               #b42219
color9               #85160f

# green
color2               #377242
color10              #25532e

# yellow
color3               #6a6535
color11              #4c4928

# blue
color4               #3860ac
color12              #234485

# magenta (red)
color5               #905201
color13              #673c0c

# cyan (blue)
color6               #3860ac
color14              #234485

## white
color7               #3a3a3a
color15              #222222
