# base settings
background           #caced5
foreground           #13161b

selection_background #babec5
selection_foreground #1f2227

cursor               #1f2227
cursor_text          #babec5

# black
color0               #caced5
color8               #aaaeb5

# red
color1               #9d1a13
color9               #6e110b

# green
color2               #2e6337
color10              #1c4524

# yellow
color3               #5b572e
color11              #3e3c20

# blue
color4               #2d5299
color12              #1a3771

# magenta (red)
color5               #7c4706
color13              #54310d

# cyan (blue)
color6               #2d5299
color14              #1a3771

## white
color7               #2b2e33
color15              #1f2227
