# base settings
background           #c9d0ca
foreground           #131713

selection_background #b9c0ba
selection_foreground #1e231f

cursor               #1e231f
cursor_text          #b9c0ba

# black
color0               #c9d0ca
color8               #a9b0aa

# red
color1               #9d1a13
color9               #6e110b

# green
color2               #2e6337
color10              #1c4524

# yellow
color3               #5b572e
color11              #3e3c20

# blue
color4               #2d5299
color12              #1a3771

# magenta (red)
color5               #7c4706
color13              #54310d

# cyan (blue)
color6               #2d5299
color14              #1a3771

## white
color7               #2a2f2b
color15              #1e231f
