# base settings
background           #2a2f2b
foreground           #eaf1ea

selection_background #373c37
selection_foreground #d9e0da

cursor               #d9e0da
cursor_text          #373c37

# black
color0               #2a2f2b
color8               #444944

# red
color1               #f37060
color9               #fea294

# green
color2               #6eb178
color10              #94cf9c

# yellow
color3               #a7a15f
color11              #c6c182

# blue
color4               #799ee3
color12              #a2bef2

# magenta (red)
color5               #d98937
color13              #f1ad6f

# cyan (blue)
color6               #799ee3
color14              #a2bef2

## white
color7               #c9d0ca
color15              #eaf1ea
